#!/usr/bin/env python3
"""
Render every per-client artefact from clients.yml.

Run via `make generate` (which supplies a container with PyYAML) or directly
with `python3 scripts/generate.py` if you have PyYAML installed locally.

Everything this writes is deterministic and safe to commit — no secrets. Agent
passwords live only in INGEST_USERS (Dokploy env), never in a generated file.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

try:
    import yaml
except ImportError:
    sys.exit(
        "generate.py needs PyYAML.\n"
        "  Use  make generate   (runs in a container, nothing to install)\n"
        "  or   pip install pyyaml"
    )

ROOT = Path(__file__).resolve().parent.parent
CLIENTS_FILE = ROOT / "clients.yml"

ID_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*$")
BANNER = "# GENERATED by scripts/generate.py from clients.yml — do not edit by hand.\n"

# prom-label-proxy pins the client label into every query it forwards.
LABEL_PROXY_IMAGE = "quay.io/prometheuscommunity/prom-label-proxy:v0.13.0"


# ── loading & validation ───────────────────────────────────────────────────

def load_clients() -> list[dict]:
    if not CLIENTS_FILE.exists():
        sys.exit(f"missing {CLIENTS_FILE}")

    doc = yaml.safe_load(CLIENTS_FILE.read_text()) or {}
    clients = doc.get("clients") or []
    if not clients:
        sys.exit("clients.yml contains no clients")

    errors: list[str] = []
    seen: set[str] = set()

    for i, c in enumerate(clients):
        cid = c.get("id")
        where = f"clients[{i}]"

        if not cid:
            errors.append(f"{where}: missing `id`")
            continue

        if not ID_RE.match(cid):
            errors.append(
                f"{where}: id '{cid}' must match [a-z0-9][a-z0-9_-]* — it becomes "
                f"a metric label, a Loki tenant and a basic-auth username"
            )
        if cid in seen:
            errors.append(f"{where}: duplicate id '{cid}'")
        seen.add(cid)

        if not c.get("name"):
            errors.append(f"{where} ({cid}): missing `name`")
        if not c.get("email"):
            errors.append(f"{where} ({cid}): missing `email` — alerts would go nowhere")

        for p in c.get("probes") or []:
            url = p.get("url") if isinstance(p, dict) else p
            if not url:
                errors.append(f"{where} ({cid}): probe without a url")
                continue
            parsed = urlparse(url)
            if parsed.scheme not in ("http", "https") or not parsed.netloc:
                errors.append(f"{where} ({cid}): probe '{url}' is not a valid http(s) URL")

        for u in c.get("grafana_users") or []:
            if not u.get("login") or not u.get("email"):
                errors.append(f"{where} ({cid}): every grafana_user needs a login and an email")

    if errors:
        sys.exit("clients.yml is invalid:\n  - " + "\n  - ".join(errors))

    return clients


def normalise_probes(client: dict) -> list[dict]:
    out = []
    for p in client.get("probes") or []:
        if isinstance(p, str):
            p = {"url": p}
        out.append({"url": p["url"], "module": p.get("module", "http_2xx")})
    return out


def tenants(clients: list[dict]) -> list[dict]:
    """Real clients — those that get an Org, a label proxy and their own emails."""
    return [c for c in clients if not c.get("internal")]


def internal_ids(clients: list[dict]) -> list[str]:
    """Your own tenants: no Org, no label proxy, alerts to you only."""
    return [c["id"] for c in clients if c.get("internal")]


# ── generators ─────────────────────────────────────────────────────────────

def gen_blackbox_scrape(clients: list[dict]) -> str:
    """
    Prometheus scrape_config_files fragment: one job per blackbox module, so
    each job can carry its own `module` param. Targets are relabelled through
    the blackbox exporter in the standard way.
    """
    by_module: dict[str, list[tuple[str, str]]] = {}
    for c in clients:
        for probe in normalise_probes(c):
            by_module.setdefault(probe["module"], []).append((probe["url"], c["id"]))

    if not by_module:
        return BANNER + "scrape_configs: []\n"

    jobs = []
    for module in sorted(by_module):
        static_configs = [
            {"targets": [url], "labels": {"client": cid}}
            for url, cid in sorted(by_module[module])
        ]
        jobs.append({
            "job_name": f"blackbox_{module}",
            "scrape_interval": "30s",
            "scrape_timeout": "15s",
            "metrics_path": "/probe",
            "params": {"module": [module]},
            "static_configs": static_configs,
            "relabel_configs": [
                # The configured URL is the probe target...
                {"source_labels": ["__address__"], "target_label": "__param_target"},
                # ...and also the human-readable instance name...
                {"source_labels": ["__param_target"], "target_label": "instance"},
                # ...while the address Prometheus actually scrapes is the exporter.
                {"target_label": "__address__", "replacement": "blackbox-exporter:9115"},
            ],
        })

    # A scrape_config_files fragment must be a mapping with a `scrape_configs`
    # key — a bare list is rejected at load time.
    return BANNER + yaml.safe_dump(
        {"scrape_configs": jobs}, sort_keys=False, default_flow_style=False
    )


def gen_clients_compose(clients: list[dict]) -> str:
    """
    One prom-label-proxy per client. Each pins `client="<id>"` server-side, so
    a client's Grafana data source cannot return anyone else's metrics even if
    the user hand-writes PromQL in Explore.
    """
    services = {}
    for c in tenants(clients):
        cid = c["id"]
        services[f"prom-label-proxy-{cid}"] = {
            "image": LABEL_PROXY_IMAGE,
            "container_name": f"em-plp-{cid}",
            "restart": "unless-stopped",
            "command": [
                "--label=client",
                f"--label-value={cid}",
                "--upstream=http://prometheus:9090",
                "--insecure-listen-address=0.0.0.0:8080",
                # Without this, dashboard template variables (label_values)
                # return nothing and every panel silently empties out.
                "--enable-label-apis",
                "--error-on-replace",
            ],
            "networks": ["monitor"],
            "logging": {
                "driver": "json-file",
                "options": {"max-size": "10m", "max-file": "3"},
            },
            "depends_on": {"prometheus": {"condition": "service_healthy"}},
        }

    header = (
        BANNER
        + "# One prom-label-proxy per client — the server-side boundary that makes\n"
        + "# a client's Grafana Org unable to see another client's metrics.\n"
    )

    if not services:
        # `include:` still needs a valid file when there are no clients yet.
        return header + "\nservices: {}\n"

    return header + "\n" + yaml.safe_dump({"services": services}, sort_keys=False, width=100)


def gen_alertmanager(clients: list[dict]) -> str:
    """
    Route tree keyed on the `client` label. Each client gets their own email
    receiver; you get a copy of everything via the ops address on each receiver.
    """
    lines: list[str] = []
    w = lines.append

    w(BANNER.rstrip())
    w("#")
    w("# Placeholders (__SMTP_*__, __OPS_EMAIL__, __GRAFANA_URL__) are substituted")
    w("# at container start by config/alertmanager/render-and-run.sh, so no")
    w("# credentials are ever written into this repo.")
    w("")
    w("global:")
    w("  resolve_timeout: 5m")
    w("  smtp_smarthost: '__SMTP_SMARTHOST__'")
    w("  smtp_from: '__SMTP_FROM__'")
    w("  smtp_auth_username: '__SMTP_USER__'")
    w("  smtp_auth_password_file: /tmp/alertmanager-smtp-password")
    w("  smtp_require_tls: __SMTP_REQUIRE_TLS__")
    w("")
    w("templates:")
    w("  - /tmp/templates/*.tmpl")
    w("")
    w("route:")
    w("  # Anything that does not match a client below still reaches you.")
    w("  receiver: ops-fallback")
    w("  group_by: ['client', 'alertname']")
    w("  # Long enough to batch a cascading failure into one email, short")
    w("  # enough that you hear about an outage promptly.")
    w("  group_wait: 45s")
    w("  group_interval: 5m")
    w("  repeat_interval: 12h")
    w("  routes:")
    w("")
    w("    # Informational events are recorded but never chase anyone.")
    w("    - matchers: ['severity = \"info\"']")
    w("      receiver: ops-only")
    w("      group_interval: 30m")
    w("      repeat_interval: 24h")
    w("")
    # Derived from `internal: true` in clients.yml, never hardcoded — a
    # matcher naming a tenant that no longer exists routes nothing, silently.
    for iid in internal_ids(clients):
        w("    # The monitoring stack's own health is your problem, not a client's.")
        w(f"    - matchers: ['client = \"{iid}\"']")
        w("      receiver: ops-only")
        w("      repeat_interval: 4h")
        w("")

    for c in tenants(clients):
        cid = c["id"]
        w(f"    # ── {c['name']} ──")
        w(f"    - matchers: ['client = \"{cid}\"']")
        w(f"      receiver: client-{cid}")
        w("      routes:")
        w("        # Critical issues repeat every 2h until acknowledged.")
        w("        - matchers: ['severity = \"critical\"']")
        w(f"          receiver: client-{cid}")
        w("          group_wait: 30s")
        w("          repeat_interval: 2h")
        w("")

    w("receivers:")
    w("")
    w("  - name: ops-fallback")
    w("    email_configs:")
    w("      - to: '__OPS_EMAIL__'")
    w("        send_resolved: true")
    w("        headers:")
    w("          Subject: '{{ template \"email.subject\" . }}'")
    w("        html: '{{ template \"email.html\" . }}'")
    w("        text: '{{ template \"email.text\" . }}'")
    w("")
    w("  - name: ops-only")
    w("    email_configs:")
    w("      - to: '__OPS_EMAIL__'")
    w("        send_resolved: true")
    w("        headers:")
    w("          Subject: '{{ template \"email.subject\" . }}'")
    w("        html: '{{ template \"email.html\" . }}'")
    w("        text: '{{ template \"email.text\" . }}'")

    for c in tenants(clients):
        cid = c["id"]
        recipients = [c["email"]] + list(c.get("extra_emails") or [])
        w("")
        w(f"  - name: client-{cid}")
        w("    email_configs:")
        w(f"      # {c['name']}")
        w(f"      - to: '{', '.join(recipients)}'")
        w("        send_resolved: true")
        w("        headers:")
        w("          Subject: '{{ template \"email.subject\" . }}'")
        w("        html: '{{ template \"email.html\" . }}'")
        w("        text: '{{ template \"email.text\" . }}'")
        w("      # You receive a copy of everything, so you find out first.")
        w("      - to: '__OPS_EMAIL__'")
        w("        send_resolved: true")
        w("        headers:")
        w("          Subject: '{{ template \"email.subject\" . }}'")
        w("        html: '{{ template \"email.html\" . }}'")
        w("        text: '{{ template \"email.text\" . }}'")

    w("")
    w("inhibit_rules:")
    w("")
    w("  # A dead host produces a storm of container and disk alerts. Report")
    w("  # the cause, suppress the symptoms — but never suppress HostDown itself.")
    w("  - source_matchers: ['alertname = \"HostDown\"']")
    w("    target_matchers: ['severity =~ \"warning|critical\"', 'alertname != \"HostDown\"']")
    w("    equal: ['client', 'instance']")
    w("")
    w("  # Don't send the warning and the critical for the same thing.")
    w("  - source_matchers: ['severity = \"critical\"']")
    w("    target_matchers: ['severity = \"warning\"']")
    w("    equal: ['client', 'instance', 'alertname']")
    w("")
    w("  # A site that is down will also be returning error statuses.")
    w("  - source_matchers: ['alertname = \"SiteDown\"']")
    w("    target_matchers: ['alertname =~ \"HTTPUnexpectedStatus|SiteSlow|SSLCertInvalid\"']")
    w("    equal: ['client', 'instance']")
    w("")
    w("  # An imminent expiry makes the 14-day warning redundant.")
    w("  - source_matchers: ['alertname = \"SSLCertExpiryImminent\"']")
    w("    target_matchers: ['alertname = \"SSLCertExpiringSoon\"']")
    w("    equal: ['client', 'instance']")
    w("")

    return "\n".join(lines)


def gen_grafana_orgs(clients: list[dict]) -> str:
    """Input for scripts/bootstrap_grafana.py (stdlib-only, so JSON not YAML)."""
    payload = {
        "clients": [
            {
                "id": c["id"],
                "name": c["name"],
                "users": [
                    {
                        "login": u["login"],
                        "email": u["email"],
                        "name": u.get("name", u["login"]),
                    }
                    for u in (c.get("grafana_users") or [])
                ],
            }
            for c in tenants(clients)
        ],
        # The admin Org's Loki data source queries every tenant at once;
        # Loki accepts a pipe-separated tenant list on read. Your own
        # internal tenants are included so their logs show up in admin too.
        "all_tenants": "|".join(c["id"] for c in clients),
    }
    return json.dumps(payload, indent=2) + "\n"


def gen_grafana_admin_datasources(clients: list[dict]) -> str:
    """
    Data sources for the admin Org (orgId 1) — your fleet-wide view.

    Prometheus is wired straight through with no label proxy, so you see every
    client. Loki is queried across all tenants at once: it accepts a
    pipe-separated tenant list in X-Scope-OrgID on the read path.

    The UIDs are deliberately fixed to `prometheus` and `loki`. `make bootstrap`
    uses the same UIDs inside each client Org, which is what lets one dashboard
    JSON work unmodified in every Org.
    """
    all_tenants = "|".join(c["id"] for c in clients)

    return BANNER + f"""apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 30s
      httpMethod: POST

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    editable: false
    jsonData:
      timeout: 60
      maxLines: 5000
      # Every tenant at once — admin view.
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: "{all_tenants}"
"""


def gen_onboarding(client: dict) -> str:
    cid = client["id"]
    probes = normalise_probes(client)
    probe_lines = "\n".join(f"- `{p['url']}` ({p['module']})" for p in probes) or "- _none configured_"
    users = client.get("grafana_users") or []
    user_lines = "\n".join(f"- {u.get('name', u['login'])} — `{u['email']}`" for u in users) or "- _none configured_"

    return f"""# Onboarding — {client['name']} (`{cid}`)

GENERATED by `make generate`. Regenerate rather than editing.

## 1. Add the ingest credential

Generate a password and append it to `INGEST_USERS` in Dokploy
(Environment tab), then redeploy the stack:

```
openssl rand -base64 24
# INGEST_USERS=...,{cid}:<that password>
```

## 2. Install the agent on each of their servers

On every host you want monitored:

```
curl -fsSL https://raw.githubusercontent.com/ThomasGerr/GrafanaPrometheusLoki/main/agent/install.sh \\
  | sudo bash -s -- \\
      --client {cid} \\
      --ingest https://ingest.example.com \\
      --password '<the password from step 1>'
```

Confirm it arrived — this should return a non-empty result within a minute:

```
docker exec em-prometheus wget -qO- 'http://localhost:9090/api/v1/query?query=up%7Bclient%3D%22{cid}%22%7D' | head -c 400
```

## 3. Create their Grafana Org and logins

On the monitoring host:

```
make bootstrap-server
```

It reaches Grafana over the stack's own network. Neither `localhost` nor the
public URL works from there: no port is published, and Cloudflare rejects the
public one. From your own machine use `GRAFANA_URL=<public url> make bootstrap`.

Passwords are generated and printed once. Send them over a channel you
consider acceptable for credentials, and have the user change it on first login.

## Alerts

Routed to `{client['email']}`, with a copy to your ops address.

## Uptime checks configured

{probe_lines}

## Grafana logins

{user_lines}
"""


# ── main ───────────────────────────────────────────────────────────────────

def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text() if path.exists() else None
    if existing == content:
        print(f"  unchanged  {path.relative_to(ROOT)}")
        return
    path.write_text(content)
    print(f"  wrote      {path.relative_to(ROOT)}")


def main() -> None:
    clients = load_clients()
    real = tenants(clients)

    print(f"clients.yml: {len(clients)} entries ({len(real)} billable tenants)")

    write(ROOT / "config/prometheus/scrape/blackbox.yml", gen_blackbox_scrape(clients))
    write(ROOT / "docker-compose.clients.yml", gen_clients_compose(clients))
    write(ROOT / "config/alertmanager/alertmanager.yml.tmpl", gen_alertmanager(clients))
    write(ROOT / "generated/grafana-orgs.json", gen_grafana_orgs(clients))
    write(
        ROOT / "config/grafana/provisioning/datasources/admin.yml",
        gen_grafana_admin_datasources(clients),
    )

    for c in real:
        write(ROOT / f"generated/onboarding/{c['id']}.md", gen_onboarding(c))

    missing_creds = [c["id"] for c in real]
    print()
    print("Next:")
    print("  1. make validate")
    print("  2. ensure INGEST_USERS has an entry for: " + ", ".join(missing_creds))
    print("  3. commit, then redeploy in Dokploy")
    print("  4. GRAFANA_URL=<your grafana> make bootstrap   (creates/updates Grafana Orgs and logins)")


if __name__ == "__main__":
    main()
